//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessRun
    {
        public int id { get; set; }
        public int IdProcess { get; set; }
        public int IdGroup { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
