//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Step()
        {
            this.TaskProcesses = new HashSet<TaskProcess>();
        }
    
        public int Id { get; set; }
        public int IdProcess { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool StartStep { get; set; }
        public Nullable<int> NextStep1 { get; set; }
        public Nullable<int> NextStep2 { get; set; }
        public int Key { get; set; }
        public string Figure { get; set; }
        public System.DateTime Created_At { get; set; }
        public System.DateTime Updated_At { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProcess> TaskProcesses { get; set; }
    }
}
