//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StepRun()
        {
            this.TaskProcessRuns = new HashSet<TaskProcessRun>();
        }
    
        public int Id { get; set; }
        public int idProcess { get; set; }
        public string Name { get; set; }
        public bool StartStep { get; set; }
        public Nullable<int> NextStep1 { get; set; }
        public Nullable<int> NextStep2 { get; set; }
        public int Key { get; set; }
        public string Figure { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> Approve_At { get; set; }
    
        public virtual ProcessRun ProcessRun { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProcessRun> TaskProcessRuns { get; set; }
    }
}
