//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepRun
    {
        public int Id { get; set; }
        public int Id_Step { get; set; }
        public int Id_Process { get; set; }
        public string Name { get; set; }
        public bool StartStep { get; set; }
        public int NextStep1 { get; set; }
        public int NextStep2 { get; set; }
        public int Key { get; set; }
        public string Figure { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
