//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagement.Content.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CWIntro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CWIntro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessManagement.Content.resources.CWIntro", typeof(CWIntro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model your processes.
        /// </summary>
        public static string Clockworks_Intro_benefit1 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick and easy to use..
        /// </summary>
        public static string Clockworks_Intro_benefit2 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses BPMN 2.0 notation..
        /// </summary>
        public static string Clockworks_Intro_benefit3 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates perfect, beautiful, complete, professional and stylish documentation..
        /// </summary>
        public static string Clockworks_Intro_benefit4 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        public static string Clockworks_Intro_benifits1 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benifits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business process modeling.
        /// </summary>
        public static string Clockworks_Intro_benifits2 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benifits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool has everything an expert in processes could ever want:.
        /// </summary>
        public static string Clockworks_Intro_benifits3 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_benifits3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Clockworks_Intro_create_button {
            get {
                return ResourceManager.GetString("Clockworks_Intro_create_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Group.
        /// </summary>
        public static string Clockworks_Intro_find_button {
            get {
                return ResourceManager.GetString("Clockworks_Intro_find_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESS PROCESS MODELING.
        /// </summary>
        public static string Clockworks_Intro_slogan1 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_slogan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MADE EASILY.
        /// </summary>
        public static string Clockworks_Intro_slogan2 {
            get {
                return ResourceManager.GetString("Clockworks_Intro_slogan2", resourceCulture);
            }
        }
    }
}
